name: Skelegram
author: DereWah
description: A skript to interface with the Telegram Bot API.
version: 1.0
main: org.derewah.skelegram.Skelegram
depend: [Skript]
commands:
  skelegram:
    description: The commands from Skelegram.